os: linux
sudo: false
language: python

matrix:
  include:
    - python: 3.6
    - python: 2.7
    - python: pypy
  fast_finish: true

install:
  - pip install pytest
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - export PATH="${HOME}/.cargo/bin:${PATH}"
  - which cargo
  - which rustc

script:
  - make test

cache:
  - pip
